# Generated by Django 4.2.8 on 2024-01-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_profile_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='calcium',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='dietary_fiber',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='iron',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='saturated_fat',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='sodium',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='trans_fat',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b1',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b2',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_c',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
